services:
  - type: web
    name: backdoor-web-signer
    env: python
    buildCommand: |
      apt-get update && apt-get install -y clang cmake libssl-dev libzip-dev libminizip-dev git git-lfs
      git lfs install
      chmod +x install_zsign.sh && ./install_zsign.sh
      pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py wsgi:app
    plan: free
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: MAX_WORKERS
        value: 2
      - key: TIMEOUT
        value: 600
      - key: LFS_REPO_PATH
        value: /tmp/lfs_storage
      - key: PORT
        value: 12000

  - type: web
    name: backdoor-web-signer-worker
    env: python
    buildCommand: |
      apt-get update && apt-get install -y clang cmake libssl-dev libzip-dev libminizip-dev git git-lfs
      git lfs install
      chmod +x install_zsign.sh && ./install_zsign.sh
      pip install -r requirements.txt
    startCommand: python worker.py
    plan: free
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - fromGroup: backdoor-web-signer
      - key: MAX_CONCURRENT_TASKS
        value: 2
      - key: LFS_REPO_PATH
        value: /tmp/lfs_storage
      - key: PORT
        value: 12001